# Generated by Django 4.0.4 on 2022-05-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passedPoints',
            field=models.ManyToManyField(blank=True, to='museum.point'),
        ),
    ]
